# Use an alpine linux distro (nice and small), that already has python as a base
FROM python:2.7-alpine

# Dependencies
ENV CONSUL_VERSION 0.5.2
ENV CONSUL_SHA256 171cf4074bfca3b1e46112105738985783f19c47f4408377241b868affa9d445

RUN apk --update add curl bash ca-certificates && \
    curl -Ls https://circle-artifacts.com/gh/andyshinn/alpine-pkg-glibc/6/artifacts/0/home/ubuntu/alpine-pkg-glibc/packages/x86_64/glibc-2.21-r2.apk > /tmp/glibc-2.21-r2.apk && \
    apk add --allow-untrusted /tmp/glibc-2.21-r2.apk && \
    rm -rf /tmp/glibc-2.21-r2.apk /var/cache/apk/*
ADD https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip /tmp/consul.zip
RUN echo "${CONSUL_SHA256}  /tmp/consul.zip" > /tmp/consul.sha256 \
  && sha256sum -c /tmp/consul.sha256 \
  && cd /bin \
  && unzip /tmp/consul.zip \
  && chmod +x /bin/consul \
  && rm /tmp/consul.zip

ENV GOMAXPROCS 2

COPY consul.d /etc/consul.d/

COPY consul-client-start.sh /usr/local/bin
RUN chmod a+x /usr/local/bin/consul-client-start.sh

VOLUME /data/consul
VOLUME /var/log/consul

EXPOSE 8300 8301 8301/udp 8302 8302/udp 8400 8500 8600 8600/udp

# Server
WORKDIR /usr/local/lib
COPY simple-service simple-service/
ENV SIMPLE_SERVICE_PORT 8080
EXPOSE 8080
