FROM alpine

ENV CONSUL_TEMPLATE_VERSION 0.11.1

RUN apk --update add bash haproxy ca-certificates unzip wget rsyslog \
  && cd /tmp \
  && wget -O consul-template.zip https://releases.hashicorp.com/consul-template/${CONSUL_TEMPLATE_VERSION}/consul-template_${CONSUL_TEMPLATE_VERSION}_linux_amd64.zip \
  && unzip consul-template.zip \
  && mv consul-template /usr/local/bin/consul-template \
  && rm -rf consul-template.zip \
  && mkdir -p /etc/haproxy.d

VOLUME /var/log/haproxy

COPY consul-template.d /etc/consul-template.d/
COPY syslog.d /etc/syslog.d/
